version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
    volumes:
      - 'mysql-data:/var/lib/mysql'
      - ./mysql-conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mongo-data:/data/db'
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    

volumes:
    mysql-data:
      driver: local
    mongo-data:
      driver: local
