version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    ports:
      - '${DB_PORT}:3306'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
volumes:
  mysql-data:
    driver: local
